dev_mode: false
engine: Qwen3Engine

seed: 42
deterministic: false

project:
  name: "qwen3-8b"
  dir: "./outputs"

log:
  interval: 1
  backends: ["terminal", "file"]
  accumulation_size: 1
  timer_window_size: 10

parallel:
  mesh:
    replicate: 1
    shard: -1
    tensor: 1

data:
  train_path: "./data/mvp-engine-llm-pretrain-dev-data/meta.json"
  text_field: "data"
  packing_tail_policy: "drop"
  packing_isolate_attention: false
  packing_isolate_position_ids: false
  max_seq_len: 8192
  batch_size: 1
  num_workers: 8

model:
  pretrained_model_name_or_path: "Qwen/Qwen3-8B-Base"
  attn_implementation: "flash_attention_2"
  load_pretrained_model: false
  gradient_checkpointing:
    enabled: true
    use_reentrant: false
  freeze_llm: false
  compile:
    enabled: false
    backend: "inductor"
    mode: "default"

optim:
  optimizer: "AdamW"
  lr: 3.0e-4
  weight_decay: 0.1
  global_batch_size: 256
  gradient_accumulation_steps: -1
  mixed_precision: "bf16"
  warmup_ratio: 0.03
  clip_grad_norm: 1.0
  loss_spike_skip_multiplier: null
  loss_spike_skip_window_size: 8
  loss_spike_skip_min_history: 3

loop:
  policy: "iter"
  total_steps: 10000

checkpoint:
  interval: 5000
  keep_n: 2
  hf_enable: true
