dev_mode: false
engine: Qwen3PTEngine

seed: 42
deterministic: false

project:
  name: "qwen3_pt-0.6b-smoke"
  dir: "./outputs"

log:
  interval: 1
  backends: ["terminal", "file"]
  accumulation_size: 1
  timer_window_size: 10

parallel:
  mesh:
    replicate: 1
    shard: 1
    tensor: 1

data:
  train_path: "/mnt/data-alpha-sg-01/team-camera/shared/mvp-engine/data/text/lance/bigcode_starcoderdata/meta.json"
  text_field: "data"
  packing_selection_strategy: "best_fit"
  packing_open_pack_limit: 8
  packing_buffer_size: 64
  max_seq_len: 2048
  batch_size: 8
  num_workers: 2

model:
  pretrained_model_name_or_path: "Qwen/Qwen3-0.6B-Base"
  attn_implementation: "sdpa"
  train_from_scratch: true
  init_seed: 42
  gradient_checkpointing:
    enabled: false
    use_reentrant: false
  freeze_llm: false
  compile:
    enabled: false
    backend: "inductor"
    mode: "default"

optim:
  lr: 5.5e-4
  weight_decay: 0.1
  gradient_accumulation_steps: 1
  mixed_precision: "bf16"
  beta1: 0.9
  beta2: 0.95
  min_lr_rate: 0.1
  warmup_steps: 10
  clip_grad_norm: 1.0

loop:
  policy: "iter"
  total_steps: 50

checkpoint:
  interval: 100000
  keep_n: 1
  hf_enable: false
