dev_mode: true
engine: PanguvlEngine

seed: 42
deterministic: false

project:
  name: "panguvl-debug"
  dir: "./outputs"

log:
  interval: 1
  backends: ["terminal"]
  accumulation_size: 1
  timer_window_size: 10

parallel:
  mesh:
    replicate: -1
    shard: 1
    tensor: 1

data:
  train_path: "/home/k00885418/projects/mvp-engine/data/Open-Bee/Bee-Training-Data-Stage1-Stage2-mm-only/synthdog_zh_processed_new/**/*.parquet"
  enable_thinking: "non-empty"
  cache: false
  shuffle_buffer: 1000
  packing: true
  packing_selection_strategy: "best_fit"
  packing_open_pack_limit: 8
  packing_buffer_size: 64
  max_seq_len: 8192
  batch_size: 1
  num_workers: 0

model:
  pretrained_model_name_or_path: "/home/k00885418/projects/test_checkpoint/OpenPangu-VL-7B-vanilla/openPangu-VL-7B"
  attn_implementation: "sdpa"
  image_max_pixels: 1048576
  gradient_checkpointing:
    enabled: false
    use_reentrant: false
  freeze_vit: true
  freeze_merger: false
  freeze_llm: true
  compile: false
  compile_backend: "inductor"
  compile_mode: "default"

optim:
  lr: 1.0e-4
  weight_decay: 0.0
  gradient_accumulation_steps: 4
  mixed_precision: "bf16"
  warmup_ratio: 0.0
  clip_grad_norm: 1.0

loop:
  policy: "iter"
  total_steps: 100

checkpoint:
  interval: 100
  keep_n: 1
  hf_enable: false
