"""GoalSpec — the execution-layer schema between natural-language goals and
runtime objects (ObjectiveSpec, engine config, eval config).

Design invariants
-----------------
- GoalSpec is the compiler's OUTPUT and the runtime's INPUT.
- MonitorSpec is a *template*; ObjectiveSpec is a *live instance* bound to a
  run_id.  The existing ObjectiveSpec / server / CLI paths stay untouched.
- Every field must be resolvable against the current engine event ontology,
  recipe capabilities, or agent server API.  No aspirational-only fields.
- Compiler-internal concepts (capability, modality, output type) do NOT
  appear here — they are consumed during compilation and resolved into
  concrete fields (recipe, stage, eval_tasks).

v1 limitations
--------------
- Monitors: threshold only (no trend/window detection).
- Custom events: schema exists, but runtime hook registration is not implemented.
-   `custom_events` must remain empty in v1.
- Actions: fire → notify.  No stop_run / scale_down.
- Lifecycle: monitors live and die with the run.
- Each monitor watches exactly one field.

Engine event ontology (source of truth: engine.py)
---------------------------------------------------
run_started      — step, epoch, artifacts.run_output_dir, metadata.total_steps
progress_updated — step, epoch, metrics.step_time_s / loss / tokens_per_sec / …
checkpoint_saved — step, epoch, artifacts.checkpoint_dir, metadata.force
run_finished     — step, epoch, artifacts.run_output_dir
run_failed       — step, epoch, metadata.exception_type

Derived events (generated by agent objective runtime)
-----------------------------------------------------
goal_violated    — when a monitor rule is breached
goal_satisfied   — when a monitor rule is met
objective_attached / eval_completed / eval_failed / report_generated
"""

from __future__ import annotations

import secrets
from dataclasses import dataclass, field
from typing import Any

_VALID_OPERATORS = {"<=", "<", ">=", ">", "==", "!="}
_VALID_TRIGGER_MODES = {"immediate", "consecutive"}
_VALID_WORKFLOW_MODES = {"train", "eval_only", "train_then_eval", "analyze_existing", "monitor_only"}
_VALID_EVAL_TRIGGERS = {"on_finish", "on_checkpoint", "manual"}


def _require_non_empty(value: str | None, *, field_name: str) -> str:
    normalized = str(value or "").strip()
    if not normalized:
        raise ValueError(f"{field_name} must not be empty")
    return normalized


def _normalize_optional(value: str | None) -> str | None:
    normalized = str(value or "").strip()
    return normalized or None


def _normalize_string_list(values: list[str]) -> list[str]:
    normalized_values: list[str] = []
    for value in values:
        normalized_values.append(_require_non_empty(value, field_name="list item"))
    return normalized_values


# ---------------------------------------------------------------------------
# MonitorSpec — a single threshold-based monitoring rule (template form)
# ---------------------------------------------------------------------------


@dataclass(slots=True)
class MonitorSpec:
    """A threshold monitor template.  Carries no run_id — that is added when
    compiled into an ObjectiveSpec at runtime.

    v1 semantics: if ``field`` breaches ``operator`` / ``target``, and the
    breach persists for ``trigger_count`` consecutive events (when
    ``trigger_mode`` is "consecutive"), the monitor fires a notification.
    """

    name: str  # "step_latency_budget"
    event_type: str  # "progress_updated"
    field: str  # "metrics.step_time_s"
    operator: str  # "<=" | "<" | ">=" | ">" | "==" | "!="
    target: float  # threshold value
    description: str | None = None  # human-readable, optional
    trigger_mode: str = "immediate"  # "immediate" | "consecutive"
    trigger_count: int = 1  # meaningful only for "consecutive"

    def __post_init__(self) -> None:
        self.name = _require_non_empty(self.name, field_name="MonitorSpec.name")
        self.event_type = _require_non_empty(self.event_type, field_name="MonitorSpec.event_type")
        self.field = _require_non_empty(self.field, field_name="MonitorSpec.field")

        self.operator = _require_non_empty(self.operator, field_name="MonitorSpec.operator")
        if self.operator not in _VALID_OPERATORS:
            raise ValueError(f"unsupported monitor operator: {self.operator}")

        self.target = float(self.target)
        self.description = _normalize_optional(self.description)

        self.trigger_mode = _require_non_empty(self.trigger_mode, field_name="MonitorSpec.trigger_mode").lower()
        if self.trigger_mode not in _VALID_TRIGGER_MODES:
            raise ValueError(f"unsupported trigger mode: {self.trigger_mode}")

        self.trigger_count = int(self.trigger_count)
        if self.trigger_count < 1:
            raise ValueError("MonitorSpec.trigger_count must be >= 1")
        if self.trigger_mode == "immediate":
            self.trigger_count = 1


# ---------------------------------------------------------------------------
# CustomEventDef — goal-scoped custom event declaration
# ---------------------------------------------------------------------------


@dataclass(slots=True)
class CustomEventDef:
    """A goal-scoped custom event definition.

    This is the forward-compatible hook contract for v2:
      source event/hook -> compute implementation -> emitted custom event

    v1 keeps the field in GoalSpec for schema stability, but runtime hook
    registration is intentionally not implemented yet.
    """

    name: str  # "activation_norm"
    source: str  # "progress_updated" | "forward_pass" | ...
    compute: str  # runtime lookup key, e.g. "layer_norm_probe"
    fields: list[str] = field(default_factory=list)  # ["metrics.layer3_norm"]

    def __post_init__(self) -> None:
        self.name = _require_non_empty(self.name, field_name="CustomEventDef.name")
        self.source = _require_non_empty(self.source, field_name="CustomEventDef.source")
        self.compute = _require_non_empty(self.compute, field_name="CustomEventDef.compute")
        self.fields = _normalize_string_list(list(self.fields))
        if not self.fields:
            raise ValueError("CustomEventDef.fields must not be empty")


# ---------------------------------------------------------------------------
# WorkflowPlan — what to execute
# ---------------------------------------------------------------------------


@dataclass(slots=True)
class WorkflowPlan:
    """Defines what the runtime should do.

    Modes
    -----
    train            — standard training run
    eval_only        — evaluate an existing checkpoint, no training
    train_then_eval  — train, then auto-evaluate on completion
    analyze_existing — generate report from prior run artifacts
    monitor_only     — attach monitors to an externally launched run
    """

    mode: str = "train"
    recipe: str | None = None  # "openbee"
    stage: str | None = None  # "stage1" | "stage2"
    source_run_id: str | None = None  # existing run (analyze_existing / monitor_only)
    source_checkpoint: str | None = None  # existing checkpoint (eval_only)
    eval_tasks: list[str] = field(default_factory=list)  # lmms-eval task ids
    eval_trigger: str = "on_finish"  # "on_finish" | "on_checkpoint" | "manual"

    def __post_init__(self) -> None:
        self.mode = _require_non_empty(self.mode, field_name="WorkflowPlan.mode")
        if self.mode not in _VALID_WORKFLOW_MODES:
            raise ValueError(f"unsupported workflow mode: {self.mode}")

        self.recipe = _normalize_optional(self.recipe)
        self.stage = _normalize_optional(self.stage)
        self.source_run_id = _normalize_optional(self.source_run_id)
        self.source_checkpoint = _normalize_optional(self.source_checkpoint)
        self.eval_tasks = _normalize_string_list(list(self.eval_tasks))

        self.eval_trigger = _require_non_empty(self.eval_trigger, field_name="WorkflowPlan.eval_trigger").lower()
        if self.eval_trigger not in _VALID_EVAL_TRIGGERS:
            raise ValueError(f"unsupported eval trigger: {self.eval_trigger}")

        if self.mode in {"train", "train_then_eval"} and not self.recipe:
            raise ValueError(f"WorkflowPlan.recipe is required for mode={self.mode}")
        if self.mode == "train_then_eval" and not self.eval_tasks:
            raise ValueError("WorkflowPlan.eval_tasks must not be empty for mode=train_then_eval")
        if self.mode == "eval_only":
            if not self.source_checkpoint:
                raise ValueError("WorkflowPlan.source_checkpoint is required for mode=eval_only")
            if not self.eval_tasks:
                raise ValueError("WorkflowPlan.eval_tasks must not be empty for mode=eval_only")
        if self.mode in {"analyze_existing", "monitor_only"} and not self.source_run_id:
            raise ValueError(f"WorkflowPlan.source_run_id is required for mode={self.mode}")


# ---------------------------------------------------------------------------
# GoalSpec — top-level container
# ---------------------------------------------------------------------------


def _generate_intent_id() -> str:
    return f"intent_{secrets.token_hex(6)}"


@dataclass(slots=True)
class GoalSpec:
    """Structured representation of a user's experiment goal.

    This is the object that sits between "goal text" and "executable runtime
    config".  A goal compiler produces it; downstream consumers are:

      1. workflow   → determines what to launch (train / eval / analyze)
      2. monitors      → compiled into ObjectiveSpec[] at runtime
      3. custom_events → reserved for future hook registration runtime

    Pipeline:
      NL goal → compiler (internal IR: TaskContract, etc.) → GoalSpec → runtime
    """

    intent_id: str
    goal_text: str  # original NL, for audit + display
    workflow: WorkflowPlan = field(default_factory=WorkflowPlan)
    monitors: list[MonitorSpec] = field(default_factory=list)
    custom_events: list[CustomEventDef] = field(default_factory=list)
    metadata: dict[str, Any] = field(default_factory=dict)

    def __post_init__(self) -> None:
        self.intent_id = _require_non_empty(self.intent_id, field_name="GoalSpec.intent_id")
        self.goal_text = _require_non_empty(self.goal_text, field_name="GoalSpec.goal_text")
        self.monitors = list(self.monitors)
        self.custom_events = list(self.custom_events)
        self.metadata = dict(self.metadata)

        if self.workflow.mode == "monitor_only" and not self.monitors:
            raise ValueError("GoalSpec.monitors must not be empty for mode=monitor_only")
        if self.custom_events:
            raise ValueError(
                "GoalSpec.custom_events is reserved for v2 hook runtime support and must be empty in v1"
            )


# ---------------------------------------------------------------------------
# Worked examples
# ---------------------------------------------------------------------------


def _example_smoke_test() -> GoalSpec:
    """Scenario 1: pure monitoring, no training.

    Goal: "monitor each training step under 0.001s; notify after 2 consecutive
           violations"
    """

    return GoalSpec(
        intent_id=_generate_intent_id(),
        goal_text="monitor each training step under 0.001 seconds; notify after 2 consecutive violations",
        workflow=WorkflowPlan(
            mode="monitor_only",
            source_run_id="openbee-ar-smoke-63180",
        ),
        monitors=[
            MonitorSpec(
                name="step_latency_budget",
                event_type="progress_updated",
                field="metrics.step_time_s",
                operator="<=",
                target=0.001,
                description="notify when training step latency exceeds 0.001s",
                trigger_mode="consecutive",
                trigger_count=2,
            ),
        ],
        metadata={"compiler": "rule_based_v1"},
    )


def _example_full_experiment() -> GoalSpec:
    """Scenario 2: train + auto-eval + monitoring.

    Goal: "训练一个视频问答模型，训练完自动评测，速度太慢提醒我"
    """

    return GoalSpec(
        intent_id=_generate_intent_id(),
        goal_text="训练一个视频问答模型，训练完自动评测，速度太慢提醒我",
        workflow=WorkflowPlan(
            mode="train_then_eval",
            recipe="openbee",
            stage="stage2",
            eval_tasks=["video_qa"],
            eval_trigger="on_finish",
        ),
        monitors=[
            MonitorSpec(
                name="step_latency_budget",
                event_type="progress_updated",
                field="metrics.step_time_s",
                operator="<=",
                target=10.0,
                description="alert when step time gets too high",
                trigger_mode="consecutive",
                trigger_count=3,
            ),
        ],
        metadata={"compiler": "llm_v1"},
    )


def _example_loss_threshold_degraded() -> GoalSpec:
    """Scenario 3 (degraded): "loss 一直不降" — v1 近似为阈值监控。

    真正的 trend detection 需要 window/trend rule type，留 v2。
    v1 compiler 将其翻译为 "loss >= 5.0 连续 10 次就报警"。

    Goal: "loss 一直不降就提醒我"
    """

    return GoalSpec(
        intent_id=_generate_intent_id(),
        goal_text="loss 一直不降就提醒我",
        workflow=WorkflowPlan(
            mode="train",
            recipe="openbee",
            stage="stage1",
        ),
        monitors=[
            MonitorSpec(
                name="loss_plateau_approx",
                event_type="progress_updated",
                field="metrics.loss",
                operator=">=",
                target=5.0,
                description="v1 degraded: approximate plateau detection via threshold",
                trigger_mode="consecutive",
                trigger_count=10,
            ),
        ],
        metadata={"compiler": "llm_v1", "degraded_scenarios": ["trend_detection"]},
    )


def _example_eval_only() -> GoalSpec:
    """Scenario 4: evaluate an existing checkpoint, no training.

    Goal: "用最新的 checkpoint 跑一下 video qa benchmark"
    """

    return GoalSpec(
        intent_id=_generate_intent_id(),
        goal_text="用最新的 checkpoint 跑一下 video qa benchmark",
        workflow=WorkflowPlan(
            mode="eval_only",
            recipe="openbee",
            source_checkpoint="/mnt/data-alpha-sg-01/team-camera/shared/mvp-engine/pretrained/Qwen3-VL-8B-Base-woDS-stage0",
            eval_tasks=["video_qa"],
            eval_trigger="manual",
        ),
        monitors=[],
        metadata={"compiler": "llm_v1", "resolution": "latest checkpoint resolved by compiler"},
    )


def _example_analyze_existing() -> GoalSpec:
    """Scenario 5: generate report from prior run, no training or eval.

    Goal: "帮我分析一下 job 63180 的训练结果"
    """

    return GoalSpec(
        intent_id=_generate_intent_id(),
        goal_text="帮我分析一下 job 63180 的训练结果",
        workflow=WorkflowPlan(
            mode="analyze_existing",
            source_run_id="openbee-ar-smoke-63180",
        ),
        monitors=[],
        metadata={"compiler": "llm_v1"},
    )
