dev_mode: false
engine: MinimalVLMEngine

seed: 42
deterministic: false

project:
  name: "minimal-vlm"
  dir: "./outputs"

log:
  interval: 1
  accumulation_size: 1
  timer_window_size: 10

parallel:
  mesh:
    replicate: -1
    shard: 1
    context: 1
    tensor: 1
  backend_kwargs:
    sequence_parallel: false
    long_context:
      enabled: false
      ulysses_degree: 1
      ring_degree: 1
      ring_impl_type: "basic"
      attn_impl: "fa"
      use_ulysses_low: true
      use_sync: false
      grad_sync: true
data:
  train_path: "./data/minimal_vlm/demo.parquet"
  max_seq_len: 2048
  batch_size: 1
model:
  pretrained_model_name_or_path: "Qwen/Qwen3-VL-2B-Instruct"
optim:
  lr: 1.0e-5
  weight_decay: 0.05
loop:
  policy: "iter"
  total_steps: 100
