# @package optim

lr: 5.0e-5
weight_decay: 0.0
global_batch_size: 256
gradient_accumulation_steps: -1
mixed_precision: "bf16"
warmup_ratio: 0.002
clip_grad_norm: 1.0
loss_spike_skip_multiplier: 2
loss_spike_skip_window_size: 10
loss_spike_skip_min_history: 3
