dev_mode: false
engine: Qwen3VLEngine
project:
  name: "qwen3vl"
data:
  dataset_type: "jsonl"
  data_path: "./recipes/qwen3_vl/data/openbee_1k/samples.jsonl"
  batch_size: 16
  num_workers: 8
  shuffle_buffer: 5000
model:
  name: "Qwen/Qwen3-VL-2B-Instruct"
  pretrained: "Qwen/Qwen3-VL-2B-Instruct"
  freeze_vit: true
  freeze_projector: false
  freeze_llm: true
optim:
  lr: 0.00001
  weight_decay: 0.05
  gradient_accumulation_steps: 1
  mixed_precision: "bf16"
  warmup_ratio: 0.1
  clip_grad_norm: 1
  compile: True
  compile_backend: "inductor"
  compile_mode: "max-autotune"
loop:
  policy: "iter"
  total_steps: 100000
  checkpoint:
    keep_n: 5
    interval: 5000
parallel:
  type: "fsdp2"
  backend_kwargs:
      reshard_after_forward: true
      mp_policy:
        param_dtype: bfloat16
        reduce_dtype: float32
        output_dtype: bfloat16
      high_precision_modules: ["LayerNorm", "RMSNorm"]
