defaults:
  - stage1
parallel:
  type: "fsdp2"
  backend_kwargs:
      reshard_after_forward: true
      mp_policy:
        param_dtype: bfloat16
        reduce_dtype: float32
        output_dtype: bfloat16
      high_precision_modules: ["LayerNorm", "RMSNorm"]
