defaults:
  - base
  - data: stage3
  - model: qwen3_vl_8b
  - model_checkpoint@model: stage2
  - model_runtime@model: full_stage3
  - optim: stage3
  - parallel: fsdp8
  - loop: dataset_sized
  - checkpoint: export
  - _self_

seed: 219
