defaults:
  - base
  - data: stage2
  - model: qwen3_vl_8b
  - model_checkpoint@model: stage1
  - model_runtime@model: full_stage2
  - optim: stage2
  - parallel: fsdp8
  - loop: dataset_sized
  - checkpoint: export
  - _self_

seed: 219
